import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

describe('bootstrap shell source', () => {
  it('keeps Markit Chinese intake copy and avoids unrelated product surfaces', () => {
    const source = readFileSync(resolve(import.meta.dirname, 'App.tsx'), 'utf8');
    expect(source).toContain('Markit');
    expect(source).toContain('把任意真实 URL 变成可点击、可标注、可导出证据的 Bug 工作台');
    expect(source).toContain('默认单端验收');
    expect(source).toContain('区块');
    expect(source).toContain('区域标注');
    expect(source).toContain('圈选');
    expect(source).toContain('快速保存');
    expect(source).toContain('撤销标注');
    expect(source).toContain('截图 / 对比证据');
    expect(source).toContain('Cmd+V 粘贴截图');
    expect(source).toContain('快速评论');
    expect(source).toContain('原始需求链接');
    expect(source).toContain('Bug 草稿');
    expect(source).toContain('保存为一个 Bug');
    expect(source).toContain('data-testid="url-input"');
    expect(source).toContain('Project Catalog');
    expect(source).toContain('可测试项目');
    expect(source).toContain('testId="catalog-project-select"');
    expect(source).toContain('直接输入 URL 仍可测试');
    expect(source).toContain('SearchableSelect');
    expect(source).toContain('mk-project-context');
    expect(source).toContain('保存归属');
    expect(source).toContain('className="mk-panel-section mk-meta-list" open');
    expect(source).toContain('projectSnapshot');
    expect(source).toContain('绑定域名');
    expect(source).toContain('项目列表');
    expect(source).toContain('groupBugsByProject');
    expect(source).toContain('mk-project-bug-list');
    expect(source).toContain('全选当前项目');
    expect(source).toContain('bulkExportBugs');
    expect(source).toContain('draftGitLabIssues');
    expect(source).toContain('submitGitLabIssues');
    expect(source).toContain('bulk-action-status');
    expect(source).toContain('停止等待');
    expect(source).toContain('IssueStatusPill');
    expect(source).toContain('截图资源');
    expect(source).toContain('currentDraft');
    expect(source).toContain('unansweredAiQuestions');
    expect(source).toContain('mergeAiDraft');
    expect(source).toContain('selectedForIssueSubmit');
    expect(source).toContain('无需重复提交');
    expect(source).toContain('提交中...');
    expect(source).toContain('返回已有 Issue');
    expect(source).toContain('bulk-assignees');
    expect(source).toContain('负责人（可选，多人用逗号）');
    expect(source).toContain('parseAssigneeInput');
    expect(source).toContain('assignees');
    expect(source).not.toMatch(/ChatComposer|project\/run/i);
  });
});
